### ISSUE TITLE
大佬，能不能个一个配置目录格式? 

### ISSUE THREAD

**Issue by Aurora209** [Dellear/UnicomTaskDocker#1]
docker 拉取后，运行提示：
没有映射config配置目录给本容器，请先按教程映射config配置目录...

**Comment by Dellear** [comment]
映射容器内/config目录到宿主机，里面要放的东西可以参照仓库中的config目录

**Comment by Dellear** [comment]
> docker 拉取后，运行提示：
> 没有映射config配置目录给本容器，请先按教程映射config配置目录...

映射容器内/config目录到宿主机，里面要放的东西可以参照仓库中的config目录

**Comment by goukey** [comment]
映射倒是可以了，现在问题是一到设定的时间，就提示./config.json文件不存在，而手动运行python main.py却正常...........

**Comment by Dellear** [comment]
> 映射倒是可以了，现在问题是一到设定的时间，就提示./config.json文件不存在，而手动运行python main.py却正常...........

定时需要这样写，cat /config/config.json > ${SCRIPT_DIR}/config.json && python ${SCRIPT_DIR}/main.py，需要把自己的配置替换到对应的config.json里

**Comment by Dellear** [comment]
> > 映射倒是可以了，现在问题是一到设定的时间，就提示./config.json文件不存在，而手动运行python main.py却正常...........
> 
> 定时需要这样写，cat /config/config.json > ${SCRIPT_DIR}/config.json && python ${SCRIPT_DIR}/main.py，需要把自己的配置替换到对应的config.json里

如果还不行，需要使用 cd ${SCRIPT_DIR} && cat /config/config.json > config.json && python main.py
