### ISSUE TITLE
请问大佬有没有详细一点的说明教程,刚接触不久,不懂.

### ISSUE THREAD

**Issue by hokifungcalvin** [Dellear/UnicomTaskDocker#4]
请问大佬有没有详细一点的说明教程,刚接触不久,不懂.

**Comment by hokifungcalvin** [comment]
docker已经安装了,库也拉了,docker-compose.yml要建在哪里?

**Comment by Dellear** [comment]
> docker已经安装了,库也拉了,docker-compose.yml要建在哪里?

那你直接使用docker命令的当时直接开启即可
